name: "Test"

on:
  push:
    branches:
    - main
    - github-actions-test
    paths-ignore:
    - 'LICENSE'
    - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
    - 'LICENSE'
    - '.gitignore'
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install package [pip]
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests with Pytest
        run: |
          coverage run -m pytest

      - name: Coverage
        run: |
          coverage report
          coverage json

      - name: Version check
        run: |
          python .github/scripts/metadata_manager

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
